general:
  prefix: '&8[&9SimpleAds&8] '
  language: "en"

title:
  fadein: 10
  stay: 70
  fadeout: 20
  sound:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP

anunce:
  sound:
    enabled: true
    sound: ENTITY_PLAYER_LEVELUP