general:
  prefix: '&8[&9SimpleAds&8] ' # Prefix for messages
  language: "en" # Language file to use (without .yml)
  update-check: true # Check for updates on startup

title: 
  fadein: 10 # Fade-in duration in ticks
  stay: 70 # Stay duration in ticks
  fadeout: 20 # Fade-out duration in ticks
  sound:
    enabled: true # Play sound on title display
    sound: ENTITY_PLAYER_LEVELUP # Sound to play

anunce:
  sound:
    enabled: true # Play sound on announcement
    sound: ENTITY_PLAYER_LEVELUP # Sound to play

# Automatic ad setup
auto-ads:
  enabled: true
  interval: 300 # Time in seconds between each ad (300s = 5 minutes)
  random: false # If true, it will choose messages randomly. If false, it will follow the order of the list.
  messages:
    - '[center]&#FF8C00&lÂ¡FOLLOW US!'
    - "[center]&7Don't forget to join our Discord:"
    - '[center]&9&ndiscord.gg/tu-servidor'
    - '[center]&#55FF55&lTIP: &7Use &a/help &7to see commands.'